rivos: Add TEST_ONLY and TEST_KASAN env variables
No need to trigger kasan builds/tests at every submission, let the
developer ask for it, this will reduce the CI duration (even if jobs are
run in parallel, kasan inline is twice as long as other jobs to build).

TEST_ONLY can be used to only test the test infrastructure to avoid
wasting time building the kernels.

Signed-off-by: Alexandre Ghiti <alexghiti@rivosinc.com>

diff --git a/rivos/gitlab-ci.yml b/rivos/gitlab-ci.yml
--- a/rivos/gitlab-ci.yml
+++ b/rivos/gitlab-ci.yml
@@ -37,6 +37,10 @@ docker-build-defconfig:
       - linux_defconfig.tar.gz
       - make_logs_defconfig.txt
     expire_in: 3 hours
+  rules:
+      - if: '$TEST_ONLY == "yes"'
+        when: never
+      - if: '$CI_COMMIT_BRANCH'
 
 docker-build-ubuntu-defconfig:
   # Use the rivos-sdk container to get the toolchains and build tools.
@@ -60,6 +64,10 @@ docker-build-ubuntu-defconfig:
       - linux_ubuntu_defconfig.tar.gz
       - make_logs_ubuntu_defconfig.txt
     expire_in: 3 hours
+  rules:
+      - if: '$TEST_ONLY == "yes"'
+        when: never
+      - if: '$CI_COMMIT_BRANCH'
 
 .kasan-conf-generic: &kasan-conf-generic
     - echo "CONFIG_KASAN=y" > kasan.conf
@@ -90,6 +98,11 @@ docker-build-ubuntu-kasan-outline-defconfig:
       - linux_ubuntu_kasan_outline_defconfig.tar.gz
       - make_logs_ubuntu_kasan_outline_defconfig.txt
     expire_in: 3 hours
+  rules:
+    - if: '$TEST_ONLY == "yes"'
+      when: never
+    - if: '$TEST_KASAN == "yes"'
+      when: on_success
 
 docker-build-ubuntu-kasan-inline-defconfig:
   # Use the rivos-sdk container to get the toolchains and build tools.
@@ -115,6 +128,11 @@ docker-build-ubuntu-kasan-inline-defconfig:
       - linux_ubuntu_kasan_inline_defconfig.tar.gz
       - make_logs_ubuntu_kasan_inline_defconfig.txt
     expire_in: 3 hours
+  rules:
+    - if: '$TEST_ONLY == "yes"'
+      when: never
+    - if: '$TEST_KASAN == "yes"'
+      when: on_success
 
 package-deb:
   extends: .deploy-deb
@@ -124,6 +142,7 @@ package-deb:
     - docker-build-ubuntu-defconfig
     - docker-build-ubuntu-kasan-outline-defconfig
     - docker-build-ubuntu-kasan-inline-defconfig
+    - sdk-linux-ubuntu-test # For TEST_ONLY to publish artifacts
   variables:
     PKG_ARCH: "all"
     PKG_DESCRIPTION: "Linux kernel image for RISCV64."
@@ -133,10 +152,10 @@ package-deb:
   before_script:
     # clean up pre-built binaries from the rivos-sdk
     - rm -rf "${INSTALL_PATH}"
-    - tar -C/ -xzf linux_defconfig.tar.gz
+    - if [[ -z "$TEST_ONLY" ]]; then tar -C/ -xzf linux_defconfig.tar.gz; fi
     - tar -C/ -xzf linux_ubuntu_defconfig.tar.gz
-    - tar -C/ -xzf linux_ubuntu_kasan_outline_defconfig.tar.gz
-    - tar -C/ -xzf linux_ubuntu_kasan_inline_defconfig.tar.gz
+    - if [[ "$TEST_KASAN" == "yes" ]]; then tar -C/ -xzf linux_ubuntu_kasan_outline_defconfig.tar.gz; fi
+    - if [[ "$TEST_KASAN" == "yes" ]]; then tar -C/ -xzf linux_ubuntu_kasan_inline_defconfig.tar.gz; fi
 
 sdk-linux-ubuntu-test:
   image: gitlab.ba.rivosinc.com:5050/rv/it/int/rivos-sdk:${SDK_BASE_TAG}
@@ -146,7 +165,15 @@ sdk-linux-ubuntu-test:
     - docker-build-ubuntu-defconfig
   script:
     - rm -rf "${INSTALL_DIR}"
-    - tar -C/ -xzf linux_ubuntu_defconfig.tar.gz
+    - |
+      if [[ "$TEST_ONLY" == "yes" ]]; then
+        curl --output artifacts.zip -L --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.ba.rivosinc.com/api/v4/projects/38/jobs/artifacts/${CI_COMMIT_REF_NAME//\//%2F}/download?job=docker-build-ubuntu-defconfig"
+        if ! unzip artifacts.zip; then
+          echo "Artifacts not found!"
+          exit -1
+        fi
+      fi
+      tar -C/ -xzf linux_ubuntu_defconfig.tar.gz
     - apt update
     - pip install fabric
     - cd rivos/linux_ci
@@ -157,6 +184,7 @@ sdk-linux-ubuntu-test:
     paths:
       - rivos/linux_ci/ubuntu_output
       - rivos/linux_ci/tests_results/
+      - linux_ubuntu_defconfig.tar.gz # used when TEST_ONLY to propagate artifacts
     expire_in: 3h
   rules:
     - if: '$UBUNTU_ARCH != "riscv64" && $CI_COMMIT_BRANCH'
@@ -182,7 +210,7 @@ sdk-linux-ubuntu-kasan-inline-test:
       - rivos/linux_ci/tests_results/
     expire_in: 3h
   rules:
-    - if: '$UBUNTU_ARCH != "riscv64" && $CI_COMMIT_BRANCH'
+    - if: '$TEST_KASAN == "yes" && $UBUNTU_ARCH != "riscv64" && $CI_COMMIT_BRANCH'
 
 sdk-linux-ubuntu-kasan-outline-test:
   image: gitlab.ba.rivosinc.com:5050/rv/it/int/rivos-sdk:${SDK_BASE_TAG}
@@ -205,7 +233,7 @@ sdk-linux-ubuntu-kasan-outline-test:
       - rivos/linux_ci/tests_results/
     expire_in: 3h
   rules:
-    - if: '$UBUNTU_ARCH != "riscv64" && $CI_COMMIT_BRANCH'
+    - if: '$TEST_KASAN == "yes" && $UBUNTU_ARCH != "riscv64" && $CI_COMMIT_BRANCH'
 
 # Rebuild the rivos-sdk image if this is the branch the SDK is using.
 # Currently the 'latest' tag from the 'rivos/main' branch.
